apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysqldbsvr
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: mysqldbsvr
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: dbpassword11
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: usermanagement-dbcreation-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: azure-disk-for-mysql-pvc
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: mysqldbsvr
  ports:
  - port: 3306
    targetPort: 3306
