apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: pavanbaloji/k8webapidemoapp:4.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: backendapisvc
spec:
  selector:
    app: backend-app
  ports:
  - name: http
    port: 8080
    targetPort: 80

