apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontendapp
        image: pavanbaloji/demofrontendapp:4.0
        env:
          - name: WebAPIBaseUrl
            value: "http://backendapisvc:8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort: 80

